### ISSUE TITLE
Not catching errors properly

### ISSUE THREAD

**Issue by Mark-H** [bramdevries/omnipay-paymill#1]
Hi @bramdevries! Thanks for this omnipay driver. I'm using it to replace my old omnipay v1 driver for paymill, but am running into issues with the error handling. They don't seem strict enough, causing failed transactions to still report successful when checking `$response->isSuccessful()`.

To be a bit more specific, it looks like it's not catching issues where the `status` on a transaction is not `success`. The Response.php isSuccessful method only checks wether there is an error in the root of the `$this->data`. See https://developers.paymill.com/en/reference/api-reference/index.html#transactions for the different values that can be set for `status`, and `response_code` which can contain one of errors that are mentioned in section 3.2 of https://developers.paymill.com/en/reference/testing/

This seems like a pretty serious issue. If you have this code accepting payments right now, I would be very careful that it has not been marking transactions as paid, when they in fact failed.

Another issue that I noticed is that `$response->getTransactionReference()` is not returning a value. This is checking `$this->data['id']` whereas the result of a successful transaction is in `$this->data['data']` (with another value `$this->data['mode']` which contains test or live), so the transaction reference should be looking at `$this->data['data']['id']` instead. Which makes me wonder if it would be more appropriate to set `$this->data` to `$this->data['data']` instead..

**Comment by bramdevries** [comment]
Fixed in 1.0.1
